# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=0.0.1
group=io.github.pia
java_version=17

# Common
minecraft_version=1.20.4
mod_name=Painting Addon
mod_author=ieshishinjin
mod_id=pia
license=MIT
credits=ieshishinjin
description=Add more Painting!
minecraft_version_range=[1.20.4, 1.21)

# Fabric
fabric_version=0.92.1+1.20.4
fabric_loader_version=0.15.3

# Forge
forge_version=49.2.0
forge_loader_version_range=[49,)
forge_version_range=[49,)

# NeoForge
neoforge_version=20.4.83-beta
neoforge_loader_version_range=[2,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
